# Generated by Django 3.0.8 on 2020-07-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskscategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='userscategorylevel',
            options={'verbose_name': 'Users  category level', 'verbose_name_plural': 'Users categories level'},
        ),
        migrations.AlterModelOptions(
            name='userstasks',
            options={'verbose_name': 'Users task', 'verbose_name_plural': 'Users tasks'},
        ),
    ]
