# Generated by Django 3.0.8 on 2020-07-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20200706_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='userscategorylevel',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='userscategorylevel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userstasks',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='userstasks',
            old_name='user_id',
            new_name='user',
        ),
    ]
