# Generated by Django 3.0.8 on 2020-07-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20200706_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstasks',
            name='task_status',
        ),
    ]
