# Generated by Django 3.0.8 on 2020-07-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_userstasks_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='answer',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='level',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='url',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
