# Generated by Django 3.0.8 on 2020-07-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_auto_20200707_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='url',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
