# Generated by Django 3.0.8 on 2020-07-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_auto_20200707_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskscategory',
            name='url',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
