# Generated by Django 3.0.8 on 2020-07-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_taskscategory_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscategorylevel',
            old_name='user_progress',
            new_name='solved_tasks',
        ),
        migrations.DeleteModel(
            name='Userstasks',
        ),
    ]
