# Generated by Django 3.0.8 on 2020-07-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20200714_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
